export const flowLinkAbi = [
  {
    type: "function",
    name: "cancelLink",
    stateMutability: "nonpayable",
    inputs: [{ name: "linkId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "createLink",
    stateMutability: "nonpayable",
    inputs: [
      { name: "recipient", type: "address" },
      { name: "amount", type: "uint256" },
      { name: "deadline", type: "uint256" },
      { name: "title", type: "string" },
      { name: "description", type: "string" },
    ],
    outputs: [{ name: "linkId", type: "uint256" }],
  },
  {
    type: "function",
    name: "getCreatorLinks",
    stateMutability: "view",
    inputs: [{ name: "creator", type: "address" }],
    outputs: [{ name: "", type: "uint256[]" }],
  },
  {
    type: "function",
    name: "getLink",
    stateMutability: "view",
    inputs: [{ name: "linkId", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "creator", type: "address" },
          { name: "recipient", type: "address" },
          { name: "amount", type: "uint256" },
          { name: "deadline", type: "uint256" },
          { name: "title", type: "string" },
          { name: "description", type: "string" },
          { name: "active", type: "bool" },
          { name: "paid", type: "bool" },
          { name: "payer", type: "address" },
          { name: "paidAt", type: "uint256" },
          { name: "receiptId", type: "bytes32" },
          { name: "createdAt", type: "uint256" },
          { name: "cancelledAt", type: "uint256" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "getLinkStatus",
    stateMutability: "view",
    inputs: [{ name: "linkId", type: "uint256" }],
    outputs: [
      { name: "exists", type: "bool" },
      { name: "active", type: "bool" },
      { name: "paid", type: "bool" },
      { name: "expired", type: "bool" },
      { name: "cancelled", type: "bool" },
    ],
  },
  {
    type: "function",
    name: "getPayerLinks",
    stateMutability: "view",
    inputs: [{ name: "payer", type: "address" }],
    outputs: [{ name: "", type: "uint256[]" }],
  },
  {
    type: "function",
    name: "isPayable",
    stateMutability: "view",
    inputs: [{ name: "linkId", type: "uint256" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "nextLinkId",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "payLink",
    stateMutability: "payable",
    inputs: [{ name: "linkId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "fallback",
    stateMutability: "payable",
  },
  {
    type: "receive",
    stateMutability: "payable",
  },
  {
    type: "event",
    name: "LinkCancelled",
    inputs: [
      { name: "linkId", type: "uint256", indexed: true },
      { name: "creator", type: "address", indexed: true },
    ],
  },
  {
    type: "event",
    name: "LinkCreated",
    inputs: [
      { name: "linkId", type: "uint256", indexed: true },
      { name: "creator", type: "address", indexed: true },
      { name: "recipient", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
      { name: "deadline", type: "uint256", indexed: false },
      { name: "title", type: "string", indexed: false },
    ],
  },
  {
    type: "event",
    name: "LinkPaid",
    inputs: [
      { name: "linkId", type: "uint256", indexed: true },
      { name: "payer", type: "address", indexed: true },
      { name: "recipient", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
      { name: "receiptId", type: "bytes32", indexed: false },
    ],
  },
  { type: "error", name: "InvalidAmount", inputs: [] },
  { type: "error", name: "InvalidDeadline", inputs: [] },
  { type: "error", name: "InvalidLink", inputs: [] },
  { type: "error", name: "InvalidRecipient", inputs: [] },
  { type: "error", name: "LinkAlreadyPaid", inputs: [] },
  { type: "error", name: "LinkExpired", inputs: [] },
  { type: "error", name: "LinkInactive", inputs: [] },
  { type: "error", name: "NotCreator", inputs: [] },
  { type: "error", name: "Reentrancy", inputs: [] },
  { type: "error", name: "TransferFailed", inputs: [] },
  { type: "error", name: "WrongPaymentAmount", inputs: [] },
] as const;
