export const flowLinkV2Abi = [
  {
    type: "function",
    name: "cancelLink",
    stateMutability: "nonpayable",
    inputs: [{ name: "linkId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "contributeGroup",
    stateMutability: "payable",
    inputs: [{ name: "linkId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "createGroupLink",
    stateMutability: "nonpayable",
    inputs: [
      { name: "recipient", type: "address" },
      { name: "goalAmount", type: "uint256" },
      { name: "deadline", type: "uint256" },
      { name: "title", type: "string" },
      { name: "description", type: "string" },
    ],
    outputs: [{ name: "linkId", type: "uint256" }],
  },
  {
    type: "function",
    name: "createInvoiceLink",
    stateMutability: "nonpayable",
    inputs: [
      { name: "recipient", type: "address" },
      { name: "amount", type: "uint256" },
      { name: "deadline", type: "uint256" },
      { name: "clientName", type: "string" },
      { name: "invoiceNumber", type: "string" },
      { name: "serviceTitle", type: "string" },
      { name: "description", type: "string" },
    ],
    outputs: [{ name: "linkId", type: "uint256" }],
  },
  {
    type: "function",
    name: "createPaymentLink",
    stateMutability: "nonpayable",
    inputs: [
      { name: "recipient", type: "address" },
      { name: "amount", type: "uint256" },
      { name: "deadline", type: "uint256" },
      { name: "title", type: "string" },
      { name: "description", type: "string" },
    ],
    outputs: [{ name: "linkId", type: "uint256" }],
  },
  {
    type: "function",
    name: "createUnlockLink",
    stateMutability: "nonpayable",
    inputs: [
      { name: "recipient", type: "address" },
      { name: "amount", type: "uint256" },
      { name: "deadline", type: "uint256" },
      { name: "title", type: "string" },
      { name: "description", type: "string" },
      { name: "successMessage", type: "string" },
      { name: "unlockUrl", type: "string" },
    ],
    outputs: [{ name: "linkId", type: "uint256" }],
  },
  {
    type: "function",
    name: "getCreatorLinks",
    stateMutability: "view",
    inputs: [{ name: "creator", type: "address" }],
    outputs: [{ name: "", type: "uint256[]" }],
  },
  {
    type: "function",
    name: "getGroupContribution",
    stateMutability: "view",
    inputs: [
      { name: "linkId", type: "uint256" },
      { name: "contributor", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "getGroupContributors",
    stateMutability: "view",
    inputs: [{ name: "linkId", type: "uint256" }],
    outputs: [{ name: "", type: "address[]" }],
  },
  {
    type: "function",
    name: "getLink",
    stateMutability: "view",
    inputs: [{ name: "linkId", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "mode", type: "uint8" },
          { name: "creator", type: "address" },
          { name: "recipient", type: "address" },
          { name: "amount", type: "uint256" },
          { name: "paidAmount", type: "uint256" },
          { name: "deadline", type: "uint256" },
          { name: "title", type: "string" },
          { name: "description", type: "string" },
          { name: "active", type: "bool" },
          { name: "paid", type: "bool" },
          { name: "payer", type: "address" },
          { name: "paidAt", type: "uint256" },
          { name: "receiptId", type: "bytes32" },
          { name: "createdAt", type: "uint256" },
          { name: "cancelledAt", type: "uint256" },
          { name: "clientName", type: "string" },
          { name: "invoiceNumber", type: "string" },
          { name: "serviceTitle", type: "string" },
          { name: "successMessage", type: "string" },
          { name: "unlockUrl", type: "string" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "getLinkStatus",
    stateMutability: "view",
    inputs: [{ name: "linkId", type: "uint256" }],
    outputs: [
      { name: "exists", type: "bool" },
      { name: "active", type: "bool" },
      { name: "paid", type: "bool" },
      { name: "expired", type: "bool" },
      { name: "cancelled", type: "bool" },
      { name: "mode", type: "uint8" },
      { name: "paidAmount", type: "uint256" },
      { name: "remainingAmount", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "getPayerLinks",
    stateMutability: "view",
    inputs: [{ name: "payer", type: "address" }],
    outputs: [{ name: "", type: "uint256[]" }],
  },
  {
    type: "function",
    name: "groupContributions",
    stateMutability: "view",
    inputs: [
      { name: "", type: "uint256" },
      { name: "", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "isPayable",
    stateMutability: "view",
    inputs: [{ name: "linkId", type: "uint256" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "nextLinkId",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "payLink",
    stateMutability: "payable",
    inputs: [{ name: "linkId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "refundGroup",
    stateMutability: "nonpayable",
    inputs: [{ name: "linkId", type: "uint256" }],
    outputs: [],
  },
  { type: "fallback", stateMutability: "payable" },
  { type: "receive", stateMutability: "payable" },
  {
    type: "event",
    name: "GroupContribution",
    inputs: [
      { name: "linkId", type: "uint256", indexed: true },
      { name: "contributor", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
      { name: "paidAmount", type: "uint256", indexed: false },
      { name: "goalAmount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "GroupFunded",
    inputs: [
      { name: "linkId", type: "uint256", indexed: true },
      { name: "recipient", type: "address", indexed: true },
      { name: "totalAmount", type: "uint256", indexed: false },
      { name: "receiptId", type: "bytes32", indexed: false },
    ],
  },
  {
    type: "event",
    name: "GroupRefunded",
    inputs: [
      { name: "linkId", type: "uint256", indexed: true },
      { name: "contributor", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "LinkCancelled",
    inputs: [
      { name: "linkId", type: "uint256", indexed: true },
      { name: "creator", type: "address", indexed: true },
    ],
  },
  {
    type: "event",
    name: "LinkCreated",
    inputs: [
      { name: "linkId", type: "uint256", indexed: true },
      { name: "creator", type: "address", indexed: true },
      { name: "recipient", type: "address", indexed: true },
      { name: "mode", type: "uint8", indexed: false },
      { name: "amount", type: "uint256", indexed: false },
      { name: "deadline", type: "uint256", indexed: false },
      { name: "title", type: "string", indexed: false },
    ],
  },
  {
    type: "event",
    name: "LinkPaid",
    inputs: [
      { name: "linkId", type: "uint256", indexed: true },
      { name: "payer", type: "address", indexed: true },
      { name: "recipient", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
      { name: "receiptId", type: "bytes32", indexed: false },
    ],
  },
  { type: "error", name: "CannotCancelFundedGroup", inputs: [] },
  { type: "error", name: "GroupAlreadyFunded", inputs: [] },
  { type: "error", name: "GroupNotExpired", inputs: [] },
  { type: "error", name: "InvalidAmount", inputs: [] },
  { type: "error", name: "InvalidDeadline", inputs: [] },
  { type: "error", name: "InvalidLink", inputs: [] },
  { type: "error", name: "InvalidMode", inputs: [] },
  { type: "error", name: "InvalidRecipient", inputs: [] },
  { type: "error", name: "InvalidTitle", inputs: [] },
  { type: "error", name: "LinkAlreadyPaid", inputs: [] },
  { type: "error", name: "LinkExpired", inputs: [] },
  { type: "error", name: "LinkInactive", inputs: [] },
  { type: "error", name: "NoContribution", inputs: [] },
  { type: "error", name: "NotCreator", inputs: [] },
  { type: "error", name: "NotGroupLink", inputs: [] },
  { type: "error", name: "Reentrancy", inputs: [] },
  { type: "error", name: "TransferFailed", inputs: [] },
  { type: "error", name: "WrongPaymentAmount", inputs: [] },
] as const;
